// ajax and loading actions
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const USER_ANSWERED = 'USER_ANSWERED';
export const LOAD_CORRECT_ANSWER_SUCCESS = 'LOAD_CORRECT_ANSWER_SUCCESS';



